### ISSUE TITLE
CORS error when following tutorial

### ISSUE THREAD

**Issue by bmarker1** [Einsteinish/react-nodejs-mysql-docker-compose#12]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/test?table=sample. (Reason: CORS request did not succeed).

I've tried a few things,  but couldn't get past it.  Ideas?

**Comment by bmarker1** [comment]
If anyone else runs into this, I had to add a volume item to the server service for node_modules
```
server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
       - /app/node_modules/
    links:
      - mysql-db
    command: npm start
```
